### ISSUE TITLE
[feature suggest] allow people to change hot keys

### ISSUE THREAD

**Issue by zzz6519003** [BinaryMuse/chrome-fast-tab-switcher#17]

**Comment by aaemnnosttv** [comment]
![image](https://user-images.githubusercontent.com/1621608/31468277-cdc82c42-aee5-11e7-9ec0-ceec3da94982.png)
![image](https://user-images.githubusercontent.com/1621608/31468294-e2ca1c90-aee5-11e7-9e7d-e76dd6a6a5e3.png)
😉

**Comment by zzz6519003** [comment]
neat!
