### ISSUE TITLE
Registry returned 404 for GET on https://registry.npmjs.org/esprima-six

### ISSUE THREAD

**Issue by launchriot** [BinaryMuse/chrome-fast-tab-switcher#18]
I can't run `npm start` successfully because of the following error:

`npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/esprima-six
npm ERR! 404 
npm ERR! 404 'esprima-six' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'derequire'`

**Comment by BinaryMuse** [comment]
@launchriot Ugh sorry about that... can you try https://github.com/BinaryMuse/chrome-fast-tab-switcher/pull/19 and let me know if it works for you?

**Comment by launchriot** [comment]
@BinaryMuse yup, that seems to have fixed it! There are some other errors as well, but they don't seem to halt the installation process. Thanks! :)
